/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrameStudMaterialeCurs.java
 *
 * Created on Apr 11, 2011, 6:37:39 PM
 */

package ui;

import controller.ControllerStudent;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextArea;

/**
 *
 * @author snoopy
 * <p>updated by snoopy to controller</p>
 */
public class FrameStudMaterialeCurs extends javax.swing.JFrame {
	private ControllerStudent c;

    /** Creates new form FrameStudMaterialeCurs */
    public FrameStudMaterialeCurs(ControllerStudent cs) {
        this.c=cs;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelCursSelected = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        materialSelect = new javax.swing.JComboBox();
        materialInfo = new javax.swing.JPanel();
        labelTitlu = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        labelMaterialText = new javax.swing.JTextArea();
        butDescarca = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SEMS :: Materiale curs", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(51, 51, 255))); // NOI18N

        jLabel1.setText("Curs selectat: ");

        labelCursSelected.setFont(new java.awt.Font("Tahoma", 1, 12));
        labelCursSelected.setText("Analiza matematica");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel3.setText("Materiale disponibile: ");

        materialSelect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Syllabus", "Conditii", "Promovare", "Etc etc" }));
        materialSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialSelectActionPerformed(evt);
            }
        });

        materialInfo.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalii material"));

        labelTitlu.setFont(new java.awt.Font("Tahoma", 1, 12));
        labelTitlu.setText("Titlu material");

        labelMaterialText.setColumns(20);
        labelMaterialText.setFont(new java.awt.Font("Arial", 0, 11));
        labelMaterialText.setRows(5);
        labelMaterialText.setText(" aici vine text text tex\nttex\ntte\ntq\nrq e\nqwe q\nweqw\n ewq\n");
        jScrollPane1.setViewportView(labelMaterialText);

        butDescarca.setText("Descarca material");

        javax.swing.GroupLayout materialInfoLayout = new javax.swing.GroupLayout(materialInfo);
        materialInfo.setLayout(materialInfoLayout);
        materialInfoLayout.setHorizontalGroup(
            materialInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(materialInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(materialInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(materialInfoLayout.createSequentialGroup()
                        .addComponent(labelTitlu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                        .addComponent(butDescarca, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE))
                .addContainerGap())
        );
        materialInfoLayout.setVerticalGroup(
            materialInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(materialInfoLayout.createSequentialGroup()
                .addGroup(materialInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(materialInfoLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(labelTitlu))
                    .addComponent(butDescarca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(materialInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelCursSelected))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(materialSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelCursSelected))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(materialSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(materialInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void materialSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialSelectActionPerformed
    	c.showComponentInfo(this);
    }//GEN-LAST:event_materialSelectActionPerformed

    /**
	 * @param materialText the materialText to set
	 */


	/**
	 * @return the materialText
	 */
	public javax.swing.JTextArea getMaterialText() {
		return labelMaterialText;
	}

	/**
	 * @param materialInfo the materialInfo to set
	 */
	public void setMaterialInfo(javax.swing.JPanel materialInfo) {
		this.materialInfo = materialInfo;
	}

	/**
	 * @return the materialInfo
	 */
	public javax.swing.JPanel getMaterialInfo() {
		return materialInfo;
	}

	/**
    * @param args the command line arguments
    */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butDescarca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCursSelected;
    private javax.swing.JTextArea labelMaterialText;
    private javax.swing.JLabel labelTitlu;
    private javax.swing.JPanel materialInfo;
    private javax.swing.JComboBox materialSelect;
    // End of variables declaration//GEN-END:variables



    public JLabel getLabelTitlu() {
        return labelTitlu;
    }

    public JTextArea getLabelMaterialText() {
        return labelMaterialText;
    }

    public JButton getButDescarca() {
        return butDescarca;
    }

    public JLabel getLabelCursSelected() {
        return labelCursSelected;
    }
    

    
}
