/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frameStudTeme.java
 *
 * Created on Apr 11, 2011, 6:21:25 PM
 */

package ui;

import controller.Controller;

/**
 *
 * @author snoopy 
 * <p>updated by othniel to controller</p>
 */
public class frameStudTeme extends javax.swing.JFrame {
	private Controller c = new Controller();
	
    /** Creates new form frameStudTeme */
    public frameStudTeme() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelTeme = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listTeme = new javax.swing.JList();
        labelCursSelectat = new javax.swing.JLabel();
        setLabelInfoTeme(new javax.swing.JPanel());
        temaNume = new javax.swing.JLabel();
        temaPentru = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        setTemaDetalii(new javax.swing.JTextArea());
        jLabel4 = new javax.swing.JLabel();
        temaTermen = new javax.swing.JLabel();
        temaButIncarca = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        temaDataIncarcare = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        temaNota = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SEMS :: Teme", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(51, 51, 255))); // NOI18N

        labelTeme.setBorder(javax.swing.BorderFactory.createTitledBorder("Teme actuale"));

        jLabel1.setText("Curs selectat");

        listTeme.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Tema 1", "Tema 2", "Tema 3" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listTeme.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listTeme.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listTemeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listTeme);

        labelCursSelectat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelCursSelectat.setText("Analiza matematica");

        javax.swing.GroupLayout labelTemeLayout = new javax.swing.GroupLayout(labelTeme);
        labelTeme.setLayout(labelTemeLayout);
        labelTemeLayout.setHorizontalGroup(
            labelTemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labelTemeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(labelTemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(labelCursSelectat))
                .addContainerGap())
        );
        labelTemeLayout.setVerticalGroup(
            labelTemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labelTemeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCursSelectat)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
        );

        getLabelInfoTeme().setBorder(javax.swing.BorderFactory.createTitledBorder("Informatii despre tema"));

        temaNume.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        temaNume.setText("Tema 1");

        temaPentru.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        temaPentru.setText("Analiza matematica");

        getTemaDetalii().setColumns(20);
        getTemaDetalii().setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        getTemaDetalii().setRows(5);
        getTemaDetalii().setText("Aici vin informatiile despre o tema\ndetalii, termen de predare....etc");
        jScrollPane2.setViewportView(getTemaDetalii());

        jLabel4.setText("Termen de predare:");

        temaTermen.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        temaTermen.setText("Saptamana 4");

        temaButIncarca.setText("Incarca rezolvare");

        jLabel6.setText("Rezolvare incarcata in:");

        temaDataIncarcare.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        temaDataIncarcare.setText("12/04/2011");

        jLabel8.setText("Nota primita:");

        temaNota.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        temaNota.setText("9");

        javax.swing.GroupLayout labelInfoTemeLayout = new javax.swing.GroupLayout(getLabelInfoTeme());
        getLabelInfoTeme().setLayout(labelInfoTemeLayout);
        labelInfoTemeLayout.setHorizontalGroup(
            labelInfoTemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labelInfoTemeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(labelInfoTemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(temaNume)
                    .addComponent(temaPentru)
                    .addGroup(labelInfoTemeLayout.createSequentialGroup()
                        .addGroup(labelInfoTemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(labelInfoTemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(temaNota)
                            .addComponent(temaDataIncarcare)))
                    .addGroup(labelInfoTemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(temaButIncarca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, labelInfoTemeLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(temaTermen))))
                .addContainerGap())
        );
        labelInfoTemeLayout.setVerticalGroup(
            labelInfoTemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labelInfoTemeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(temaPentru)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(temaNume)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(labelInfoTemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(temaTermen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(labelInfoTemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(temaDataIncarcare))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(labelInfoTemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(temaNota))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(temaButIncarca)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTeme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(getLabelInfoTeme(), javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(getLabelInfoTeme(), javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTeme, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listTemeValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listTemeValueChanged
    	c.enableAssignmentActions(this);
    }//GEN-LAST:event_listTemeValueChanged

    /**
	 * @param labelInfoTeme the labelInfoTeme to set
	 */
	public void setLabelInfoTeme(javax.swing.JPanel labelInfoTeme) {
		this.labelInfoTeme = labelInfoTeme;
	}

	/**
	 * @return the labelInfoTeme
	 */
	public javax.swing.JPanel getLabelInfoTeme() {
		return labelInfoTeme;
	}

	/**
	 * @param temaDetalii the temaDetalii to set
	 */
	public void setTemaDetalii(javax.swing.JTextArea temaDetalii) {
		this.temaDetalii = temaDetalii;
	}

	/**
	 * @return the temaDetalii
	 */
	public javax.swing.JTextArea getTemaDetalii() {
		return temaDetalii;
	}

	/**
    * @param args the command line arguments
    */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelCursSelectat;
    private javax.swing.JPanel labelInfoTeme;
    private javax.swing.JPanel labelTeme;
    private javax.swing.JList listTeme;
    private javax.swing.JButton temaButIncarca;
    private javax.swing.JLabel temaDataIncarcare;
    private javax.swing.JTextArea temaDetalii;
    private javax.swing.JLabel temaNota;
    private javax.swing.JLabel temaNume;
    private javax.swing.JLabel temaPentru;
    private javax.swing.JLabel temaTermen;
    // End of variables declaration//GEN-END:variables

}
